### ISSUE TITLE
session 好像有点问题

### ISSUE THREAD

**Issue by jackluo2012** [hobo-go/echo-mw#1]
Works/golang/src/github.com/hobo-go/echo-mw/session/session.go:73: http.Request.Body is a field, not a method
Works/golang/src/github.com/hobo-go/echo-mw/session/session.go:73: cannot use request (type engine.Request) as type *http.Request in field value
Works/golang/src/github.com/hobo-go/echo-mw/session/session.go:77: cannot use response (type io.Writer) as type http.ResponseWriter in field value:
	io.Writer does not implement http.ResponseWriter (missing Header method)

**Comment by hb-chen** [comment]
是不是用的echo V2版本？

**Comment by jackluo2012** [comment]
从入门到放弃

**Comment by hb-chen** [comment]
😅
用最新的版本也不行吗？

**Comment by yuvista** [comment]
我用的是  V3 也存在这个问题

**Comment by hb-chen** [comment]
V3应该没有engine.Request了
